### ISSUE TITLE
Port glitches while doing port mapping

### ISSUE THREAD

**Issue by JorgePe** [JorgePe/SBrick-Stress-Test#1]
Default configuration (4 slides, 1 port each slide, all slides = 0, all revert checkboxes off) if we are doing port mapping there is a glitch each time we select one port (Power Functions LED blinks, E-motor spins 3 or 4 degrees).

**Comment by JorgePe** [comment]
Seems related to gui.py ports_stop or more deeply to sbrick.py Stop

**Comment by JorgePe** [comment]
Don't understand why but if guy,pi refresh sends a STOP to all ports after port mapping changes there are some quick glitches at SBrick ports.
If we just reset slide bars then at next Sync ports will also be reset. Not sure if the reset of the slide also triggers the Sync, could it be the reason?

**Comment by szigetigabor** [comment]
like this in the refresh method:

if(self.configchanged.get() == True):
  ...
  self.ports_stop()    

  # redraw it all
  self.draw_slides()
  self.configchanged.set(False)

I have eliminated the port_stop line with # and it sould works.

**Comment by JorgePe** [comment]
It seems ok, I'm closing it.
